/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author 544231740
 */
public class inicial extends javax.swing.JFrame {

    /**
     * Creates new form inicial
     */
    public inicial() {
        initComponents();
        new Thread(){
            public void run(){
                for(int i=0; i<=101; i++){
                    try {
                        sleep(60);
                        Progress.setValue(i);
                        
                        if(Progress.getValue()<=30){
                            Status.setText("Bem vindo...");
                        } else 
                            if(Progress.getValue()<=60){
                                Status.setText("Carregando a biblioteca de perguntas...");
                            } else
                                if(Progress.getValue()<=90){
                                    Status.setText("Pesquisa Concluida...");
                                } else {
                                    Status.setText("Boa sorte...");
                                }
                    }catch (InterruptedException ex){                       
                    }           
                }
                    pergunta1 ig = new pergunta1();
                    ig.setVisible(true);
                    dispose();
                
    }
        }.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Status = new javax.swing.JLabel();
        Progress = new javax.swing.JProgressBar();
        TituloGame = new javax.swing.JLabel();
        Status3 = new javax.swing.JLabel();
        Status2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pimba");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 0, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1200, 676));
        setResizable(false);
        getContentPane().setLayout(null);

        Status.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Status.setText(" ");
        getContentPane().add(Status);
        Status.setBounds(440, 600, 380, 30);
        getContentPane().add(Progress);
        Progress.setBounds(430, 600, 390, 30);

        TituloGame.setBackground(new java.awt.Color(255, 255, 255));
        TituloGame.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TituloGame.setForeground(new java.awt.Color(255, 255, 255));
        TituloGame.setText("Hackadores de HTML");
        getContentPane().add(TituloGame);
        TituloGame.setBounds(420, 40, 380, 70);

        Status3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Status3.setText("Status:");
        getContentPane().add(Status3);
        Status3.setBounds(360, 590, 80, 50);

        Status2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/programmer-wallpaper1200.png"))); // NOI18N
        Status2.setText("jLabel2");
        getContentPane().add(Status2);
        Status2.setBounds(0, 0, 1200, 676);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progress;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel Status2;
    private javax.swing.JLabel Status3;
    private javax.swing.JLabel TituloGame;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
