/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author 544231740
 */
public class pergunta1 extends javax.swing.JFrame {
    String ponto1 = "1";
    /**
     * Creates new form pergunta1
     */
    public pergunta1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pergunta = new javax.swing.JLabel();
        ContadorVidas = new javax.swing.JLabel();
        Vidas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pontos = new javax.swing.JLabel();
        op1 = new javax.swing.JCheckBox();
        op4 = new javax.swing.JCheckBox();
        op2 = new javax.swing.JCheckBox();
        op3 = new javax.swing.JCheckBox();
        opcao1 = new javax.swing.JLabel();
        opcao2 = new javax.swing.JLabel();
        opcao3 = new javax.swing.JLabel();
        opcao4 = new javax.swing.JLabel();
        conferir = new javax.swing.JButton();
        html = new javax.swing.JLabel();
        selecione = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 676));
        setMinimumSize(new java.awt.Dimension(1200, 676));
        getContentPane().setLayout(null);

        Pergunta.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Pergunta.setForeground(new java.awt.Color(255, 255, 255));
        Pergunta.setText("01 - Oque é HTML ?");
        getContentPane().add(Pergunta);
        Pergunta.setBounds(50, 60, 335, 40);

        ContadorVidas.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        ContadorVidas.setForeground(new java.awt.Color(255, 255, 255));
        ContadorVidas.setText("03");
        getContentPane().add(ContadorVidas);
        ContadorVidas.setBounds(630, 40, 50, 40);

        Vidas.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Vidas.setForeground(new java.awt.Color(255, 255, 255));
        Vidas.setText("Vidas");
        getContentPane().add(Vidas);
        Vidas.setBounds(610, -10, 100, 70);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pontos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1060, 0, 120, 50);

        pontos.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        pontos.setForeground(new java.awt.Color(255, 255, 255));
        pontos.setText("00");
        getContentPane().add(pontos);
        pontos.setBounds(1090, 40, 40, 50);

        op1.setForeground(new java.awt.Color(255, 255, 255));
        op1.setText("jCheckBox1");
        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });
        getContentPane().add(op1);
        op1.setBounds(360, 240, 20, 20);

        op4.setText("jCheckBox2");
        op4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op4ActionPerformed(evt);
            }
        });
        getContentPane().add(op4);
        op4.setBounds(360, 360, 20, 23);

        op2.setText("jCheckBox2");
        getContentPane().add(op2);
        op2.setBounds(360, 280, 20, 23);

        op3.setText("jCheckBox2");
        op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op3ActionPerformed(evt);
            }
        });
        getContentPane().add(op3);
        op3.setBounds(360, 320, 20, 23);

        opcao1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        opcao1.setForeground(new java.awt.Color(255, 255, 255));
        opcao1.setText("Linguagem utilizada por hackers");
        getContentPane().add(opcao1);
        opcao1.setBounds(390, 230, 760, 30);

        opcao2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        opcao2.setForeground(new java.awt.Color(255, 255, 255));
        opcao2.setText("Linguagem Orientada a Objetos");
        getContentPane().add(opcao2);
        opcao2.setBounds(390, 270, 730, 40);

        opcao3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        opcao3.setForeground(new java.awt.Color(255, 255, 255));
        opcao3.setText("Linguagem de marcação Web");
        getContentPane().add(opcao3);
        opcao3.setBounds(390, 310, 730, 40);

        opcao4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        opcao4.setForeground(new java.awt.Color(255, 255, 255));
        opcao4.setText("Linguagem para desenvolvimento Back-End");
        getContentPane().add(opcao4);
        opcao4.setBounds(390, 350, 750, 40);

        conferir.setForeground(new java.awt.Color(255, 0, 51));
        conferir.setText("Proxima");
        conferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conferirActionPerformed(evt);
            }
        });
        getContentPane().add(conferir);
        conferir.setBounds(980, 550, 140, 50);

        html.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/940979-256.png"))); // NOI18N
        html.setText("jLabel8");
        getContentPane().add(html);
        html.setBounds(60, 190, 260, 270);

        selecione.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        selecione.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(selecione);
        selecione.setBounds(370, 520, 510, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/R3cpQ9R1200.gif"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1200, 675);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op1ActionPerformed

    private void op4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op4ActionPerformed

    private void op3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op3ActionPerformed

    private void conferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conferirActionPerformed
       
                        // SELECTED //
        
        if (op3.isSelected()){
            
            String ponto = "01";
            pontos.setText(ponto);
            op3.setSelected(false);
            
                        // PERGUNTA 02 //
            
            String Perg = "02 - Oque é CSS";
            Pergunta.setText(Perg);
            
                       //SET TEXT DAS OPCOES//
            
                String opcao01 = "Linguagem para estilizar fotos";
                String opcao02 = "Folha de Estilo em Cascata";
                String opcao03 = "Linguagem de estilização PHP";
                String opcao04 = "Linguagem do Paint";

                opcao1.setText(opcao01);
                opcao2.setText(opcao02);
                opcao3.setText(opcao03);
                opcao4.setText(opcao04);
                                  
                    // PERGUNTA 03 //
                
                    if (op2.isSelected()){         
                        
                        String ponto2 = "02";
                        pontos.setText(ponto2);
                                                
                                String Perg03 = "03 - Oque é Banco de Dados";
                                Pergunta.setText(Perg03); 
                            
                        
                                        //SET TEXT DAS OPCOES//
                        
                            String opcao05 = "Conjunto de arquivos relacionados entre si ";
                            String opcao06 = "Banco de sentar";
                            String opcao07 = "Banco de guardar dardos";
                            String opcao08 = "Banco do Brasil";

                                opcao1.setText(opcao01);
                                opcao2.setText(opcao02);
                                opcao3.setText(opcao03);
                                opcao4.setText(opcao04);                        
                                                   
                }
                
                   
                        
                    
            
            
            
         
            
            
            
            
            
            
        } if (op3.isSelected() || op4.isSelected() || op1.isSelected()){
            String vida = "02";
            ContadorVidas.setText(vida);
            
                          // PERGUNTA 02 //
            
            String Perg = "02 - Oque é CSS";
            Pergunta.setText(Perg);
            
                       //SET TEXT DAS OPCOES//
            
                String opcao01 = "Linguagem para estilizar fotos";
                String opcao02 = "Folha de Estilo em Cascata";
                String opcao03 = "Linguagem de estilização PHP";
                String opcao04 = "Linguagem do Paint";

                opcao1.setText(opcao01);
                opcao2.setText(opcao02);
                opcao3.setText(opcao03);
                opcao4.setText(opcao04);
                
                        
                
                
                
                
        } 
    }//GEN-LAST:event_conferirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pergunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pergunta1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContadorVidas;
    private javax.swing.JLabel Pergunta;
    private javax.swing.JLabel Vidas;
    private javax.swing.JButton conferir;
    private javax.swing.JLabel html;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox op1;
    private javax.swing.JCheckBox op2;
    private javax.swing.JCheckBox op3;
    private javax.swing.JCheckBox op4;
    private javax.swing.JLabel opcao1;
    private javax.swing.JLabel opcao2;
    private javax.swing.JLabel opcao3;
    private javax.swing.JLabel opcao4;
    private javax.swing.JLabel pontos;
    private javax.swing.JLabel selecione;
    // End of variables declaration//GEN-END:variables
}
